name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip and deploy to Azure
      env:
        AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
        AZURE_WEBAPP_RG: ${{ secrets.AZURE_WEBAPP_RG }}
        AZURE_WEBAPP_PLAN: ${{ secrets.AZURE_WEBAPP_PLAN }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        zip -r app.zip .
        az webapp deploy --name $PULSARABOT --resource-group $PULSARA.AI --src-path app.zip --type zip --query 'zipDeploy' --output json
